<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('products')->truncate();
        Schema::enableForeignKeyConstraints();
        $products = [
            [
                'name' => 'Brosur Art Paper',
                'slug' => 'brosur-art-paper',
                'sub_kategori_id' => 1, 
                'description' => 'Kertas Art Paper A3, Fullcolor, Ukuran Desain Custom, 1 Sisi',
                'price' => 6000,
                'unit' => 'lbr',
                'minimum_order' => 1,
                'image' => 'brosur art paper.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kartu Nama Ivory (1 Muka)',
                'slug' => 'kartu-nama-ivory-1-muka',
                'sub_kategori_id' => 1,
                'description' => 'Kertas Ivory, Fullcolor, 1 Sisi, 1 Box isi 100 Lembar',
                'price' => 50000,
                'unit' => 'box',
                'minimum_order' => 1,
                'image' => 'kartu nama ivory 1 muka.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kartu Nama Ivory (2 Muka)',
                'slug' => 'kartu-nama-ivory-2-muka',
                'sub_kategori_id' => 1,
                'description' => 'Kertas Ivory, Fullcolor, 2 Sisi, 1 Box isi 100 Lembar',
                'price' => 70000,
                'unit' => 'box',
                'minimum_order' => 1,
                'image' => 'kartu nama ivory 2 muka.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Poster Art Paper',
                'slug' => 'poster-art-paper',
                'sub_kategori_id' => 1,
                'description' => '-',
                'price' => 5000,
                'unit' => 'lbr',
                'minimum_order' => 1,
                'image' => 'poster art paper.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Poster Ivory',
                'slug' => 'poster-ivory',
                'sub_kategori_id' => 1,
                'description' => 'Kertas Ivory, Fullcolor, Ukuran A3, 1 Sisi',
                'price' => 10000,
                'unit' => 'lbr',
                'minimum_order' => 1,
                'image' => 'poster ivory.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blocknote Biasa (1 Warna)',
                'slug' => 'blocknote-biasa-1-Warna',
                'sub_kategori_id' => 2,
                'description' => 'Kertas HVS 70gr, Cetak 1 Warna, Minimal Order: 33 Buku Isi 30 Lembar',
                'price' => 10000,
                'unit' => 'pcs',
                'minimum_order' => 33,
                'image' => 'blocknote biasa 1 warna.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blocknote Biasa (Full Color)',
                'slug' => 'blocknote-biasa-full-color',
                'sub_kategori_id' => 2,
                'description' => 'Kertas HVS 80gr, Cetak Fullcolor, Minimal Order: 33 Buku Isi 30 Lembar',
                'price' => 18000,
                'unit' => 'pcs',
                'minimum_order' => 33,
                'image' => 'blocknote biasa full color.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blocknote Spiral (1 Warna)',
                'slug' => 'blocknote-spiral-1-Warna',
                'sub_kategori_id' => 2,
                'description' => 'Kertas HVS 70gr, Cetak 1 Warna, Minimal Order: 33 Buku Isi 30 Lembar',
                'price' => 13000,
                'unit' => 'pcs',
                'minimum_order' => 33,
                'image' => 'blocknote spiral 1 warna.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blocknote Spiral (Full Color)',
                'slug' => 'blocknote-spiral-full-color',
                'sub_kategori_id' => 2,
                'description' => 'Kertas HVS 80gr, Cetak Fullcolor, Minimal Order: 33 Buku Isi 30 Lembar',
                'price' => 15000,
                'unit' => 'pcs',
                'minimum_order' => 33,
                'image' => 'blocknote spiral full color.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Yasin Lengkap Hardcover Bludru',
                'slug' => 'buku-yasin-lengkap-hardcover-bludru',
                'sub_kategori_id' => 3,
                'description' => 'Kertas Art Paper, Hardcover',
                'price' => 30000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'yasin lengkap hardcover blusdru.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Yasin Lengkap Softcover Custom',
                'slug' => 'buku-yasin-lengkap-softcover-custom',
                'sub_kategori_id' => 3,
                'description' => 'Kertas Art Paper, Hardcover',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'yasin lengkap softcover.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Yasin Standar Hardcover Biasa',
                'slug' => 'buku-yasin-standar-hardcover-biasa',
                'sub_kategori_id' => 3,
                'description' => 'Kertas Art Paper, Hardcover',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'yasin standar hardcover biasa.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Yasin Standar Softcover Custom',
                'slug' => 'buku-yasin-standar-softcover-custom',
                'sub_kategori_id' => 3,
                'description' => 'Kertas HVS, Softcover',
                'price' => 15000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'yasin standar softcover.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Nota Buram',
                'slug' => 'buku-nota-buram',
                'sub_kategori_id' => 4,
                'description' => 'Kertas Buram, 1 Warna, Minimal Order: 1 rim',
                'price' => 125000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'nota buram.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Nota HVS',
                'slug' => 'buku-nota-hvs',
                'sub_kategori_id' => 4,
                'description' => 'Kertas HVS Putih, 1 Warna, Minimal Order: 1 rim',
                'price' => 150000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'nota hvs.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Nota NCR (2 Ply)',
                'slug' => 'buku-nota-ncr-2-ply',
                'sub_kategori_id' => 4,
                'description' => 'Kertas NCR 2 ply (Top, Buttom), 1 Warna, Minimal Order: 1 rim',
                'price' => 280000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'nota ncr 2 ply.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Nota NCR (3 Ply)',
                'slug' => 'buku-nota-ncr-3-ply',
                'sub_kategori_id' => 4,
                'description' => 'Kertas NCR 3(Tiga) ply (Top, Midle, Buttom), 1(Satu) Warna, Nomerator, Minimal Order: 1(Satu) rim',
                'price' => 450000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'nota ncr 3 ply.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karcis Art Paper (Full Color)',
                'slug' => 'karcis-art-paper-full-color',
                'sub_kategori_id' => 5,
                'description' => 'Kertas Art Paper, Cetak Fullcolor, Nomerator, Minimal Order: 1 Rim',
                'price' => 850000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'karcis art paper full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karcis HVS (1 Warna)',
                'slug' => 'karcis-hvs-1-warna',
                'sub_kategori_id' => 5,
                'description' => 'Kertas HVS Putih, Cetak 1 Warna, Nomerator, Minimal Order: 1 Rim',
                'price' => 175000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'karcis hvs 1 warna.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karcis HVS (Full Color)',
                'slug' => 'karcis-hvs-full-color',
                'sub_kategori_id' => 5,
                'description' => 'Kertas HVS Putih, Cetak Fullcolor, Nomerator, Minimal Order: 1 Rim',
                'price' => 650000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'karcis hvs full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kupon HVS (1 Warna)',
                'slug' => 'kupon-hvs-1-warna',
                'sub_kategori_id' => 5,
                'description' => '-',
                'price' => 175000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'kupon hvs 1 warna.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kupon HVS (Full Color)',
                'slug' => 'kupon-hvs-full-color',
                'sub_kategori_id' => 5,
                'description' => '-',
                'price' => 600000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'kupon hvs full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiket Art Paper (Full Color)',
                'slug' => 'tiket-art-paper-full-color',
                'sub_kategori_id' => 5,
                'description' => '-',
                'price' => 850000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'tiket art paper full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiket HVS (1 Warna)',
                'slug' => 'tiket-hvs-1-warna',
                'sub_kategori_id' => 5,
                'description' => '-',
                'price' => 175000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'tiket hvs 1 warna.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiket HVS (Full Color)',
                'slug' => 'tiket-hvs-full-color',
                'sub_kategori_id' => 5,
                'description' => '-',
                'price' => 600000,
                'unit' => 'rim',
                'minimum_order' => 1,
                'image' => 'tiket hvs full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stiker Camel',
                'slug' => 'stiker-camel',
                'sub_kategori_id' => 6,
                'description' => 'Stiker Meteran',
                'price' => 120000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'stiker camel.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stiker Maxdecal',
                'slug' => 'stiker-maxdecal',
                'sub_kategori_id' => 6,
                'description' => 'Stiker Meteran',
                'price' => 130000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'stiker maxdecal.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cutting Stiker',
                'slug' => 'cutting-stiker',
                'sub_kategori_id' => 7,
                'description' => 'Stiker Vinyl/Kromo/Ivory A3',
                'price' => 5000,
                'unit' => 'lbr A3',
                'minimum_order' => 1,
                'image' => 'cutting stiker.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stiker Kromo',
                'slug' => 'stiker-kromo',
                'sub_kategori_id' => 7,
                'description' => 'Stiker Kromo A3',
                'price' => 15000,
                'unit' => 'lbr',
                'minimum_order' => 1,
                'image' => 'stiker kromo.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stiker Vinyl',
                'slug' => 'stiker-vinyl',
                'sub_kategori_id' => 7,
                'description' => 'Stiker Vinyl A3',
                'price' => 20000,
                'unit' => 'lbr',
                'minimum_order' => 1,
                'image' => 'stiker vinyl.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kalender Dinding Blangko',
                'slug' => 'kalender-dinding-blangko',
                'sub_kategori_id' => 8,
                'description' => 'Kertas Art Paper, Sablon 1(Satu) warna, Minimal Pemesanan : 100 pcs',
                'price' => 10000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => 'kalender dinding blangko.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kalender Dinding Custom (4 Halaman)',
                'slug' => 'kalender-dinding-custom-4-halaman',
                'sub_kategori_id' => 8,
                'description' => 'Kertas Art Paper, Fullcolor, Klem, Ukuran: 33x48 cm, Isi 4(Empat) Lembar',
                'price' => 20000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'kalender dinding custom 4 hal.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kalender Dinding Custom (6 Halaman)',
                'slug' => 'kalender-dinding-custom-6-halaman',
                'sub_kategori_id' => 8,
                'description' => 'Kertas Art Paper, Fullcolor, Klem, Ukuran: 33x48 cm, Isi 6(Enam) Lembar',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'kalender dinding custom 6 hal.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kalender Meja Blangko',
                'slug' => 'kalender-meja-blangko',
                'sub_kategori_id' => 9,
                'description' => 'Kertas Ivory, Spiral, Minimal Order: 100 pcs',
                'price' => 15000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => 'kalender meja blangko.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banner',
                'slug' => 'banner',
                'sub_kategori_id' => 10,
                'description' => 'Flex 280gsm, Belum Ada Desain',
                'price' => 20000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'banner.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banner + Design',
                'slug' => 'banner-+-design',
                'sub_kategori_id' => 10,
                'description' => 'Flex 280gsm, Sudah Ada Desain',
                'price' => 25000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'banner desain.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banner Papan Informasi',
                'slug' => 'banner-papan-informasi',
                'sub_kategori_id' => 10,
                'description' => 'Flex 280gsm, Rangka Kayu, Lis Alumunium',
                'price' => 100000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'banner papan informasi.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banner Segitiga',
                'slug' => 'banner-segitiga',
                'sub_kategori_id' => 10,
                'description' => 'Flex 280gsm, Rangka Kayu, 2(Dua) Sisi',
                'price' => 125000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'banner segitiga.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Roll Banner',
                'slug' => 'paket-roll-banner',
                'sub_kategori_id' => 10,
                'description' => 'Bahan: Jerman',
                'price' => 280000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'paket roll banner.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket X/Y Bannner',
                'slug' => 'paket-x-banner',
                'sub_kategori_id' => 10,
                'description' => 'Bahan/Material: Flex 280gsm, Stand X/Y Banner',
                'price' => 90000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'paket x banner.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bendera (Full Color)',
                'slug' => 'bendera-full-color',
                'sub_kategori_id' => 11,
                'description' => 'Kain Satin/Tetron, Fullcolor, Ukuran: 120x80 cm',
                'price' => 125000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'bendera full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Layur 1 Muka (Full Color)',
                'slug' => 'layur-1-muka-full-color',
                'sub_kategori_id' => 11,
                'description' => 'Kain Satin/Tetron, Fullcolor',
                'price' => 70000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'layur 1 muka full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Layur 2 Muka (1 Warna)',
                'slug' => 'layur-2-muka-1-warna',
                'sub_kategori_id' => 11,
                'description' => 'Kain Tetron, 1(Satu) warna',
                'price' => 60000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'layur 2 muka 1 warna.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spanduk (1 Warna)',
                'slug' => 'spanduk-1-warna',
                'sub_kategori_id' => 11,
                'description' => '-',
                'price' => 50000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'spanduk 1 warna.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spanduk (Full Color)',
                'slug' => 'spanduk-full-color',
                'sub_kategori_id' => 11,
                'description' => '-',
                'price' => 65000,
                'unit' => 'm',
                'minimum_order' => 1,
                'image' => 'spanduk full color.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Jersey (1 Warna)',
                'slug' => 'sablon-jersey-1-warna',
                'sub_kategori_id' => 12,
                'description' => 'Cat Quaret, Sablon 1 Warna',
                'price' => 10000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'sablon jersey 1 warna.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Jersey (Full Color)',
                'slug' => 'sablon-jersey-full-color',
                'sub_kategori_id' => 12,
                'description' => 'Bahan/Material: DTF Fullcolor',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'sablon jersey full color.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Kaos (1 Warna)',
                'slug' => 'sablon-kaos-1-warna',
                'sub_kategori_id' => 12,
                'description' => 'Cat Quaret, Sablon 1 Warna',
                'price' => 10000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'sablon kaos 1 warna.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Kaos (Full Color)',
                'slug' => 'sablon-kaos-full-color',
                'sub_kategori_id' => 12,
                'description' => 'Bahan/Material: DTF Fullcolor',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'sablon kaos full color.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Sablon Tas Spunbond',
                'slug' => 'paket-sablon-tas-spunbond',
                'sub_kategori_id' => 13,
                'description' => 'Tas spunbond, Sablon 1 Warna, Minimal Order: 1 Lusin',
                'price' => 10000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'paket sablon tas spunbond.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Plastic',
                'slug' => 'sablon-plastic',
                'sub_kategori_id' => 13,
                'description' => 'Cat Cilon, Sablon 1 Warna, Minimal Order: 1000 pcs',
                'price' => 300,
                'unit' => 'lbr',
                'minimum_order' => 1000,
                'image' => 'sablon plastik.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Tas Spunbond',
                'slug' => 'sablon-tas-spunbond',
                'sub_kategori_id' => 13,
                'description' => 'Sablon 1 Warna, Minimal Order: 1 Lusin',
                'price' => 4000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'sablon tas spunbond.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Payung (Jumbo, 1 Warna, 2 sisi)',
                'slug' => 'paket-payung-jumbo-1-warna-2-sisi',
                'sub_kategori_id' => 14,
                'description' => 'Polyster, Handle Plastik, Ukuran: 130x95 cm, Sablon 1 Warna, Sablon 2 Sisi, Minimal Order: 1 Lusin',
                'price' => 60000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'paket payung jumbo 1 warna 2 sisi.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Payung (Jumbo, Full Color, 2 sisi)',
                'slug' => 'paket-payung-jumbo-full-color-2-sisi',
                'sub_kategori_id' => 14,
                'description' => 'Polyster, Handle Plastik, Ukuran: 130x95 cm, Sablon Fullcolor, Sablon 2 Sisi, Minimal Order: 1 Lusin',
                'price' => 75000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'paket payung jumbo full color 2 sisi.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Payung (Sedang, 1 Warna, 2 sisi)',
                'slug' => 'paket-payung-sedang-1-warna-2-sisi',
                'sub_kategori_id' => 14,
                'description' => 'Polyster, Handle Plastik, Ukuran: 100x80 cm, Sablon 1 Warna, Sablon 2 Sisi, Minimal Order: 1 Lusin',
                'price' => 45000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'paket payung sedang 1 warna 2 sisi.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Payung (Sedang, Full Color, 2 sisi)',
                'slug' => 'paket-payung-sedang-full-color-2-sisi',
                'sub_kategori_id' => 14,
                'description' => 'Polyster, Handle Plastik, Ukuran: 100x80 cm, Sablon Fullcolor, Sablon 2 Sisi, Minimal Order: 1 Lusin',
                'price' => 55000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'paket payung sedang full color 2 sisi.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Payung (1 Warna 2 Sisi)',
                'slug' => 'sablon-payung-1-warna-2-sisi',
                'sub_kategori_id' => 14,
                'description' => 'Sablon 1 Warna, 2 Sisi, Minimal Order: 1 Lusin',
                'price' => 5000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'sablon payung 1 warna 2 sisi.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sablon Payung (Full Color 2 Sisi)',
                'slug' => 'sablon-payung-full-color-2-sisi',
                'sub_kategori_id' => 14,
                'description' => 'Sablon Fullcolor, 2 Sisi, Minimal Order: 1 Lusin',
                'price' => 15000,
                'unit' => 'pcs',
                'minimum_order' => 12,
                'image' => 'sablon payung full color 2 sisi.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gelas Biasa (Bening)',
                'slug' => 'gelas-biasa-bening',
                'sub_kategori_id' => 15,
                'description' => 'Sablon 1 Warna, Minimal Order: 100 pcs',
                'price' => 5000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => 'gelas biasa bening.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gelas Biasa (Doff)',
                'slug' => 'gelas-biasa-doff',
                'sub_kategori_id' => 15,
                'description' => 'Sablon 1 Warna, Minimal Order: 100 pcs',
                'price' => 6000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => 'gelas biasa doff.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gelas Cantel Biasa (Bening)',
                'slug' => 'gelas-cantel-biasa-bening',
                'sub_kategori_id' => 15,
                'description' => 'Sablon 1 Warna, Minimal Order: 100 pcs',
                'price' => 6000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => 'gelas cantel biasa bening.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gelas Cantel Biasa (Doff)',
                'slug' => 'gelas-cantel-biasa-doff',
                'sub_kategori_id' => 15,
                'description' => 'Sablon 1 Warna, Minimal Order: 100 pcs',
                'price' => 7000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => 'gelas cantel biasa doff.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mug',
                'slug' => 'mug',
                'sub_kategori_id' => 15,
                'description' => 'Sablon Fullcolor',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'mug.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blangko Undangan Khitanan',
                'slug' => 'blangko-undangan-khitanan',
                'sub_kategori_id' => 16,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => 'blangko undangan khitanan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '01 Blangko Undangan Pernikahan',
                'slug' => '01-blangko-undangan-pernikahan',
                'sub_kategori_id' => 16,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => '01 blangko undangan pernikahan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '02 Blangko Undangan Pernikahan',
                'slug' => '02-blangko-undangan-pernikahan',
                'sub_kategori_id' => 16,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => '02 blangko undangan pernikahan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '03 Blangko Undangan Pernikahan',
                'slug' => '03-blangko-undangan-pernikahan',
                'sub_kategori_id' => 16,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => '03 blangko undangan pernikahan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '01 Undangan Pernikahan',
                'slug' => '01-undangan-pernikahan',
                'sub_kategori_id' => 17,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => '01 undangan pernikahan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '02 Undangan Pernikahan',
                'slug' => '02-undangan-pernikahan',
                'sub_kategori_id' => 17,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => '02 undangan pernikahan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '03 Undangan Pernikahan',
                'slug' => '03-undangan-pernikahan',
                'sub_kategori_id' => 17,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => '03 undangan pernikahan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '04 Undangan Pernikahan',
                'slug' => '04-undangan-pernikahan',
                'sub_kategori_id' => 17,
                'description' => 'Kertas BC, Cetak 1 Warna, Minimal Order: 100 Lembar',
                'price' => 3000,
                'unit' => 'pcs',
                'minimum_order' => 100,
                'image' => '04 undangan pernikahan.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'White Board (1 Muka)',
                'slug' => 'white-board-1-muka)',
                'sub_kategori_id' => 18,
                'description' => 'Triplek White Board: 4mm, Ukuran 2.44x1.22 m, Rangka Besi, 1 Sisi, Roda',
                'price' => 1200000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'white board 1 muka.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'White Board (2 Muka)',
                'slug' => 'white-board-2-muka)',
                'sub_kategori_id' => 18,
                'description' => 'Triplek White Board: 4mm, Ukuran 2.44x1.22 m, Rangka Besi, 1 Sisi, Roda',
                'price' => 1400000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'white board 2 muka.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '1 Muka + Tiang',
                'slug' => '1-muka-+-tiang',
                'sub_kategori_id' => 19,
                'description' => 'Rangka Besi, Seng, Tiang besi, 1 muka',
                'price' => 800000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => '1 muka tiang.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '1 Muka Tanpa Tiang',
                'slug' => '1-muka-tanpa-tiang',
                'sub_kategori_id' => 19,
                'description' => 'Rangka Besi, Seng, Tiang besi, 1(Satu) muka',
                'price' => 650000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => '1 muka tanpa tiang.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '2 Muka + Tiang',
                'slug' => '2-muka-+-tiang',
                'sub_kategori_id' => 19,
                'description' => 'Rangka Besi, Seng, Tiang Besi, 2(Dua) muka',
                'price' => 1100000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => '2 muka tiang.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Papan Nama Sekolah',
                'slug' => 'paket-papan-nama-sekolah',
                'sub_kategori_id' => 19,
                'description' => 'Rangka Besi, Seng, Tiang Besi, 1(Satu) muka',
                'price' => 3500000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'paket papan nama sekolah.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Papan Rambu - Rambu (1 Muka)',
                'slug' => 'papan-rambu-rambu-1-muka',
                'sub_kategori_id' => 19,
                'description' => 'Rangka Besi, Seng, 1(Satu) muka',
                'price' => 400000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'papan rambu-rambu 1 muka.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Data Keuangan Masjid',
                'slug' => 'data-keuangan-masjid',
                'sub_kategori_id' => 20,
                'description' => 'Triplek White Board, Ukuran: 2.44 x 1.22 m, Rangka Besi, Lis Alumunium, Stiker',
                'price' => 900000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'data keuangan masjid.jpg',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Papan Petunjuk',
                'slug' => 'papan-petunjuk',
                'sub_kategori_id' => 21,
                'description' => 'Akrilik 2mm, 1 Muka, Ukuran: 30x15 cm',
                'price' => 60000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'papan petunjuk.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Papan Prasasti',
                'slug' => 'papan-prasasti',
                'sub_kategori_id' => 21,
                'description' => 'Akrilik 2mm, 1 Muka, Ukuran: 30x40 cm',
                'price' => 150000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'papan prasasti.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ID Card PVC',
                'slug' => 'id-card-pvc',
                'sub_kategori_id' => 22,
                'description' => 'PVC, Minimal Order: 25 pcs',
                'price' => 15000,
                'unit' => 'pcs',
                'minimum_order' => 25,
                'image' => 'id card pvc.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lanyard Custom',
                'slug' => 'lanyard-custom',
                'sub_kategori_id' => 22,
                'description' => 'Bahan: Tissue, Minimal Order: 10 pcs',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 10,
                'image' => 'lanyard custom.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket ID Card B2',
                'slug' => 'paket-id-card-b2',
                'sub_kategori_id' => 22,
                'description' => 'Card Holder Mika, Ivory, Gantungan ID Card, Minimal Order: 10 pcs',
                'price' => 8000,
                'unit' => 'pcs',
                'minimum_order' => 10,
                'image' => 'paket id card b2.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket ID Card B3',
                'slug' => 'paket-id-card-b3',
                'sub_kategori_id' => 22,
                'description' => 'Card Holder Mika, Ivory, Gantungan ID Card, Minimal Order: 10 pcs',
                'price' => 10000,
                'unit' => 'pcs',
                'minimum_order' => 10,
                'image' => 'paket id card b3.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket ID Card PVC',
                'slug' => 'paket-id-card-pvc',
                'sub_kategori_id' => 22,
                'description' => 'Bahan/Material: Card Holder Mika, PVC, Gantungan ID Card, Minimal Order: 25 pcs',
                'price' => 35000,
                'unit' => 'pcs',
                'minimum_order' => 25,
                'image' => 'paket id card pvc.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Name Tag Magnet',
                'slug' => 'name-tag-magnet',
                'sub_kategori_id' => 23,
                'description' => 'Name Tag Resin',
                'price' => 35000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'name tag magnet.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Name Tag Mika',
                'slug' => 'name-tag-mika',
                'sub_kategori_id' => 23,
                'description' => 'Name Tag Mika',
                'price' => 15000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'name tag mika.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Name Tag Pin',
                'slug' => 'name-tag-pin',
                'sub_kategori_id' => 23,
                'description' => 'Name Tag Peniti',
                'price' => 25000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'name tag pin.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stempel Flash (Lingkaran)',
                'slug' => 'stampel-flash-lingkaran',
                'sub_kategori_id' => 24,
                'description' => 'Stempel Flash Bulat',
                'price' => 125000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'stampel flash lingkaran.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stempel Flash (Panjang)',
                'slug' => 'stampel-flash-panjang',
                'sub_kategori_id' => 24,
                'description' => 'Stempel Flash Panjang',
                'price' => 125000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'stampel flash persegi panjang.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stempel Kayu (Lingkaran)',
                'slug' => 'stampel-kayu-lingkaran',
                'sub_kategori_id' => 24,
                'description' => 'Stempel Kayu Biasa Bulat',
                'price' => 40000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'stampel kayu lingkaran.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stempel Kayu (Panjang)',
                'slug' => 'stampel-kayu-panjang',
                'sub_kategori_id' => 24,
                'description' => 'Stempel Kayu Biasa Panjang',
                'price' => 40000,
                'unit' => 'pcs',
                'minimum_order' => 1,
                'image' => 'stampel kayu persegi panjang.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        Schema::disableForeignKeyConstraints();
        DB::table('products')->insert($products);
        Schema::enableForeignKeyConstraints();
    }
}